version: "3"
services:

  # Server
  myna-node:
    image: mynalink/node:v1
    container_name: myna-node
    env_file:
      - .env
    hostname: myna
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./db:/opt/myna/db
      - ./cache:/opt/myna/cache
      - ./log:/opt/myna/log
    group_add:
      - "0"
    ports:
      - 80:80
      - 81:81
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    extra_hosts:
      - host.docker.internal:host-gateway
