global:
  scrape_interval:     15s
  external_labels:
    monitor: 'myna-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: [ '127.0.0.1:9090' ]
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'host.docker.internal:9100' ]
  - job_name: 'myna'
    scrape_interval: 30s
    static_configs:
      - targets: [ 'host.docker.internal:81' ]
