global:
  scrape_interval:     15s
  external_labels:
    monitor: 'piper-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']