{
 "title": "Piper",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_token_count{job=\"piper\"}, instance)"
    }
   },
   {
    "name": "agent_name",
    "label": "Agent Name",
    "query": {
     "query": "label_values(agent_token_success_count{}, name)"
    }
   },
   {
    "name": "proxy_id",
    "label": "Proxy ID",
    "query": {
     "query": "label_values(proxy_success_count{}, id)"
    }
   },
   {
    "name": "template_id",
    "label": "Template ID",
    "query": {
     "query": "label_values(template_token_success_count{}, id)"
    }
   },
   {
    "name": "task_id",
    "label": "Task ID",
    "query": {
     "query": "label_values(task_token_success_count{}, id)"
    }
   },
   {
    "name": "index_name",
    "label": "Index Name",
    "query": {
     "query": "label_values(index_success_count{}, name)"
    }
   },
   {
    "name": "account_id",
    "label": "Account ID",
    "query": {
     "query": "label_values(account_success_count{}, id)"
    }
   },
   {
    "name": "template_name",
    "label": "Template Name",
    "query": {
     "query": "label_values(template_token_success_count{id=~\"$template_id\"}, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(node_token_count{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Distributors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(distributor_token_queuing_size{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Agents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(agent_token_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] success"
    },
    {
     "expr": "increase(agent_token_failure_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] failure"
    }
   ]
  },
  {
   "title": "Agent [$agent_name]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(agent_token_success_count{name=~\"$agent_name\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(agent_token_failure_count{name=~\"$agent_name\",instance=~\"$node\"}[10m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Agents Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(agent_token_queuing_size{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Proxy Success Stat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(proxy_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy Timeout Stat",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(proxy_timeout_count{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy [$proxy_id] Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(proxy_inbound_bytes{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "inbound"
    },
    {
     "expr": "increase(proxy_outbound_bytes{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "outbound"
    }
   ]
  },
  {
   "title": "Proxy [$proxy_id]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(proxy_success_count{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(proxy_banned_count{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "failure"
    },
    {
     "expr": "increase(proxy_timeout_count{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "timeout"
    },
    {
     "expr": "increase(proxy_changeIp_success_count{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "change IP success"
    },
    {
     "expr": "increase(proxy_changeIp_failure_count{id=~\"$proxy_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "change IP failure"
    }
   ]
  },
  {
   "title": "Proxy Outbound Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(proxy_outbound_bytes{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy Inbound Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(proxy_inbound_bytes{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxy Banned Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(proxy_banned_count{instance=~\"$node\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxies Change IP Stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(proxy_changeIp_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[ {{name}} ] success"
    },
    {
     "expr": "increase(proxy_changeIp_failure_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[ {{name}} ] failure"
    }
   ]
  },
  { "title": "Templates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Templates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(template_token_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] success"
    },
    {
     "expr": "increase(template_token_failure_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] failure"
    }
   ]
  },
  {
   "title": "Template [$template_id]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(template_token_success_count{id=~\"$template_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(template_token_failure_count{id=~\"$template_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(task_token_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] success"
    },
    {
     "expr": "increase(task_token_failure_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] failure "
    }
   ]
  },
  {
   "title": "Task [$task_id]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(task_token_success_count{id=~\"$task_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(task_token_failure_count{id=~\"$task_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Indices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Indices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(index_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] success"
    },
    {
     "expr": "increase(index_failure_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] failure"
    }
   ]
  },
  {
   "title": "Index [$index_name]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(index_success_count{name=~\"$index_name\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(index_failure_count{name=~\"$index_name\",instance=~\"$node\"}[10m])",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Accounts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Accounts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(account_success_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] success"
    },
    {
     "expr": "increase(account_frozen_count{instance=~\"$node\"}[10m])",
     "legendFormat": "[{{name}}] frozen"
    }
   ]
  },
  {
   "title": "Account [$account_id]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(account_success_count{name=~\"$account_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "success"
    },
    {
     "expr": "increase(account_frozen_count{name=~\"$account_id\",instance=~\"$node\"}[10m])",
     "legendFormat": "frozen"
    }
   ]
  }
 ]
}